all:
  hosts:
    node1:
      ansible_host: 158.160.9.108
      ip: 10.129.0.41
      access_ip: 10.129.0.41
    node2:
      ansible_host: 84.201.162.224
      ip: 10.129.0.39
      access_ip: 10.129.0.39
    node3:
      ansible_host: 89.169.162.62
      ip: 10.129.0.38
      access_ip: 10.129.0.38
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
